function Publish-CurrentBenchmarkReport {
    param(
        [Parameter(Mandatory = $true)][string]$RunReportPath,
        [Parameter(Mandatory = $true)][string]$DestinationPath
    )
    if (!(Test-Path -LiteralPath $RunReportPath -PathType Leaf)) {
        throw "Benchmark results JSON was not generated by this run at $RunReportPath"
    }
    try {
        $parsed = Get-Content -LiteralPath $RunReportPath -Raw | ConvertFrom-Json -ErrorAction Stop
    } catch {
        throw "Benchmark results JSON from this run is invalid at $RunReportPath. $($_.Exception.Message)"
    }
    if ($parsed.success -ne $true -or $parsed.totalScenarios -ne 8 -or $parsed.scenarios.Count -ne 8) {
        throw "Benchmark results JSON from this run does not contain eight successful scenarios: $RunReportPath"
    }
    $null = New-Item -ItemType Directory -Force -Path (Split-Path $DestinationPath -Parent)
    Copy-Item -LiteralPath $RunReportPath -Destination $DestinationPath -Force
    return $parsed
}

function Resolve-CurrentReleaseJar {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string]$ModId,
        [Parameter(Mandatory = $true)][string]$ModVersion
    )
    $expectedName = "$($ModId.Trim())-$($ModVersion.Trim()).jar"
    $expectedPath = Join-Path $ProjectRoot "build/libs/$expectedName"
    if (!(Test-Path -LiteralPath $expectedPath -PathType Leaf)) {
        throw "Current production release jar was not generated at $expectedPath"
    }
    return Get-Item -LiteralPath $expectedPath
}
